// REGISTER //
export const ON_USER_REGISTER = 'ON_USER_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
// REGISTER //


// LOGIN //
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// LOGIN //

// GENERAL //
export const USER_LOGOUT = 'USER_LOGOUT';
export const IS_LOADING = 'IS_LOADING';
export const NOT_LOADING = 'NOT_LOADING';
export const NAV_ITEM_CHANGE = 'NAV_ITEM_CHANGE';
// GENERAL //

// MOVIES //
export const ON_MOVIE_PLAY = 'ON_MOVIE_PLAY';
export const CALC_MOVIE_VIEWS = 'CALC_MOVIE_VIEWS';
// MOVIES //